; LITTLE MASTER
; Map: LoRom | SlowRom
; Checksum: $409DBF62
; Exported by Mesen2-Diz

lorom

incsrc "lm3_labels.asm"

incsrc "lm3_bank80.asm"
incsrc "lm3_bank81.asm"
incsrc "lm3_bank82.asm"
incsrc "lm3_bank83.asm"
incsrc "lm3_bank84.asm"
incsrc "lm3_bank85.asm"
incsrc "lm3_bank86.asm"
incsrc "lm3_bank87.asm"
incsrc "lm3_bank88.asm"
incsrc "lm3_bank89.asm"
incsrc "lm3_bank8A.asm"
incsrc "lm3_bank8B.asm"
incsrc "lm3_bank8C.asm"
incsrc "lm3_bank8D.asm"
incsrc "lm3_bank8E.asm"
incsrc "lm3_bank8F.asm"
incsrc "lm3_bank90.asm"
incsrc "lm3_bank91.asm"
incsrc "lm3_bank92.asm"
incsrc "lm3_bank93.asm"
incsrc "lm3_bank94.asm"
incsrc "lm3_bank95.asm"
incsrc "lm3_bank96.asm"
incsrc "lm3_bank97.asm"
incsrc "lm3_bank98.asm"
incsrc "lm3_bank99.asm"
incsrc "lm3_bank9A.asm"
incsrc "lm3_bank9B.asm"
incsrc "lm3_bank9C.asm"
incsrc "lm3_bank9D.asm"
incsrc "lm3_bank9E.asm"
incsrc "lm3_bank9F.asm"
incsrc "lm3_bankA0.asm"
incsrc "lm3_bankA1.asm"
incsrc "lm3_bankA2.asm"
incsrc "lm3_bankA3.asm"
incsrc "lm3_bankA4.asm"
incsrc "lm3_bankA5.asm"
incsrc "lm3_bankA6.asm"
incsrc "lm3_bankA7.asm"
incsrc "lm3_bankA8.asm"
incsrc "lm3_bankA9.asm"
incsrc "lm3_bankAA.asm"
incsrc "lm3_bankAB.asm"
incsrc "lm3_bankAC.asm"
incsrc "lm3_bankAD.asm"
incsrc "lm3_bankAE.asm"
incsrc "lm3_bankAF.asm"
incsrc "lm3_bankB0.asm"
incsrc "lm3_bankB1.asm"
incsrc "lm3_bankB2.asm"
incsrc "lm3_bankB3.asm"
incsrc "lm3_bankB4.asm"
incsrc "lm3_bankB5.asm"
incsrc "lm3_bankB6.asm"
incsrc "lm3_bankB7.asm"
incsrc "lm3_bankB8.asm"
incsrc "lm3_bankB9.asm"
incsrc "lm3_bankBA.asm"
incsrc "lm3_bankBB.asm"
incsrc "lm3_bankBC.asm"
incsrc "lm3_bankBD.asm"
incsrc "lm3_bankBE.asm"
incsrc "lm3_bankBF.asm"
