# interaction-text

[table]
name = "interaction-text"
type = "pointer"

[encoding]
table_file = "en_data/eng.tbl"
fallback = "jp_data/jap.tbl"
terminator = 0x00

[pointers]
offset = 0x1BBB4
count = 119
size = 2

[data]
offset = 0x1C0F1

[section]
