# scene-messages

[table]
name = "scene-messages"
type = "pointer"

[encoding]
table_file = "en_data/eng.tbl"
fallback = "jp_data/jap.tbl"
terminator = 0x00

[pointers]
offset = 0x1BD00
count = 33
size = 2

[data]
offset = 0x1F2B7

[section]
